//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gp.QueryToolbox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gp.QueryToolbox.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndGroup.
        /// </summary>
        internal static string AndGroupXElementName {
            get {
                return ResourceManager.GetString("AndGroupXElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string CriteriaLeftXAttributeName {
            get {
                return ResourceManager.GetString("CriteriaLeftXAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string CriteriaOperatorXAttributeName {
            get {
                return ResourceManager.GetString("CriteriaOperatorXAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string CriteriaRightXAttributeName {
            get {
                return ResourceManager.GetString("CriteriaRightXAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        internal static string CriteriaXElementName {
            get {
                return ResourceManager.GetString("CriteriaXElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria element invalid : Missing attribute &apos;{0}&apos;.
        /// </summary>
        internal static string Err_CriteriaMissingAttribute {
            get {
                return ResourceManager.GetString("Err_CriteriaMissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XElement name. {0} expected, {1} founded..
        /// </summary>
        internal static string Err_InvalidXElementName {
            get {
                return ResourceManager.GetString("Err_InvalidXElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow operator..
        /// </summary>
        internal static string Err_UnknowOperator {
            get {
                return ResourceManager.GetString("Err_UnknowOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string QueryXElementName {
            get {
                return ResourceManager.GetString("QueryXElementName", resourceCulture);
            }
        }
    }
}
